jobs:
  api-checks:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Install
      run: cd RobinServer && rm -rf node_modules && yarn install --frozen-lockfile

    - name: Prettier
      run: cd RobinServer && yarn ci-prettier

    - name: Lint
      run: cd RobinServer && yarn ci-lint
